language: node_js
node_js:
  - stable
deploy:
    provider: s3
    on:
      branch: production
    access_key_id: $access_key_id
    secret_access_key: $secret_access_key
    bucket: resilientcoasts.org
    acl: public_read
    local_dir: dist
    skip_cleanup: true
