language: node_js
install:
  # Tell npm to ignore package-lock.json to avoid making local file
  # changes that would dirty the git workspace.
  - npm config set package-lock false
  - npm install
node_js:
  - stable
deploy:
    provider: s3
    on:
      branch: production
    access_key_id: $access_key_id
    secret_access_key: $secret_access_key
    bucket: resilientcoasts.org
    acl: public_read
    local_dir: dist
    skip_cleanup: true
